### ISSUE TITLE
책 125p. 2번째 line 

### ISSUE THREAD

**Issue by expitly** [slipp/web-application-server#6]
안녕하세요

책 125p 2번째 line

if("/user/create".startsWith(url)){
=> if(url.startsWith("/user/create")){

로 변경되는게 맞는것같아 문의드립니다.

**Comment by javajigi** [comment]
@expitly 
제보하신 것처럼 변경하는 것이 맞습니다.

이전에 제보해 주신 분이 있어 [1판 1쇄 - 오타 및 정정할 내용](https://github.com/slipp/jwp-book/blob/master/revisions/revision1-1.md)에 반영했습니다.

제보 감사합니다.
